# В этом месте вам необходимо настроить маршрутизацию /api/<resource>
server {
    location /api/photos/{
        proxy_pass http://app1:8000/;
    }

    location /api/other/{
        proxy_pass http://app2:8000/;
    }
}
